image: maven:latest

stages:
  - build
  - test
  - notification

cache:
  paths:
    - target/

build:
  stage: build
  script:
    - mvn compile
  only:
    - master
    - development

test:
  stage: test
  script:
    - mvn test
  only:
    - master
    - development

success_notification:
  stage: notification
  script:
    - wget https://raw.githubusercontent.com/DiscordHooks/gitlab-ci-discord-webhook/master/send.sh
    - chmod +x send.sh
    - ./send.sh success $WEBHOOK_URL
  when: on_success

failure_notification:
  stage: notification
  script:
    - wget https://raw.githubusercontent.com/DiscordHooks/gitlab-ci-discord-webhook/master/send.sh
    - chmod +x send.sh
    - ./send.sh failure $WEBHOOK_URL
  when: on_failure