image: maven:latest

stages:
  - build
  - test

cache:
  paths:
    - target/

build:
  stage: build
  script:
    - mvn compile
  only:
    - master
    - development

test:
  stage: test
  script:
    - mvn test
  only:
    - master
    - development