version: '3'

networks: 
    app-tier:
        driver: bridge

services:
    db:
        image: mysql
        command: --default-authentication-plugin=mysql_native_password
        environment:
            - MYSQL_USER=prodiga
            - MYSQL_PASSWORD=SuperGeheimesPassword123NacktNiemand!!
            - MYSQL_DATABASE=prodiga
            - MYSQL_ROOT_PASSWORD=root
        ports:
            - 3306:3306
        networks: 
            - app-tier

    server:
        build: .
        image: prodiga_server:1.0
        ports:
            - 8081:8081
        depends_on:
            - db
        restart: always
        networks: 
            - app-tier
