version: '3'

networks: 
    app-tier:
        driver: bridge

services:
    db:
        image: mysql
        command: --default-authentication-plugin=mysql_native_password
        environment:
            - MYSQL_USER=prodiga
            - 'MYSQL_PASSWORD=SuperGeheimesPassword123NacktNiemand!!'
            - MYSQL_DATABASE=prodiga
            - MYSQL_ROOT_PASSWORD=root
        ports:
            - 3306:3306
        restart: always
        networks: 
            - app-tier
        volumes:
            - ./dockersql:/docker-entrypoint-initdb.d

    server:
        build: .
        image: prodiga_server:1.0
        ports:
            - 8080:8080
        depends_on:
            - db
        restart: always
        environment:
            SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/prodiga?useLegacyDatetimeCode=false&serverTimezone=UTC
            SPRING_DATASOURCE_USERNAME: prodiga
            SPRING_DATASOURCE_PASSWORD: SuperGeheimesPassword123NacktNiemand!!
        networks: 
            - app-tier
